name: cupplus
description: "Networking app for professional matchmakers"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  supabase_flutter: ^2.8.2
  go_router: ^14.8.1
  dynamic_color: ^1.7.0
  flutter_screenutil: ^5.9.3
  intl: ^0.20.2
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.3
  google_sign_in: ^6.2.2
  kakao_flutter_sdk_user: ^1.9.6
  shared_preferences: ^2.5.4
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  gal: ^2.3.0
  http: ^1.3.0
  path_provider: ^2.1.5
  crypto: ^3.0.7
  purchases_flutter: ^9.14.0
  url_launcher: ^6.3.2
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.14
  riverpod_generator: ^2.6.3
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - .env.production
    - assets/splash/
